# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: germinator
version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

snapshot:
  version_template: "{{ incpatch .Version }}-next"

metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X gitlab.com/amoconst/germinator/internal/version.Version={{.Version}}
      - -X gitlab.com/amoconst/germinator/internal/version.Commit={{.Commit}}
      - -X gitlab.com/amoconst/germinator/internal/version.Date={{.Date}}
    main: ./cmd
    binary: germinator
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - LICENSE*
      - README.md
      - INSTALL.md

checksum:
  name_template: 'germinator_{{.Version}}_checksums.txt'
  algorithm: sha256

sboms:
  - artifacts: archive
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_sbom.spdx.json"

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^build:'
      - '^Merge pull request'
      - '^Merge branch'
  groups:
    - title: Features
      order: 0
    - title: Bug Fixes
      order: 100
    - title: Other
      order: 999

release:
  gitlab:
    owner: amoconst
    name: germinator
  mode: replace
  name_template: "v{{ .Version }}"
  extra_files:
    - glob: install.sh

gomod:
  proxy: true
